/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import services.PayrollProcessor;

/**
 *
 * @author brianjancarlos
 */
public class PayrollManagement extends javax.swing.JFrame {

    /**
     * Creates new form PayrollManagement
     */
    public PayrollManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_payrolmgmt = new javax.swing.JPanel();
        btn_process_payroll = new javax.swing.JButton();
        jMonthChooser_payroll = new com.toedter.calendar.JMonthChooser();
        jYearChooser_payroll = new com.toedter.calendar.JYearChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpanel_payrolmgmt.setBorder(javax.swing.BorderFactory.createTitledBorder("Payroll Managment"));

        btn_process_payroll.setText("Process Payroll");
        btn_process_payroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_process_payrollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_payrolmgmtLayout = new javax.swing.GroupLayout(jpanel_payrolmgmt);
        jpanel_payrolmgmt.setLayout(jpanel_payrolmgmtLayout);
        jpanel_payrolmgmtLayout.setHorizontalGroup(
            jpanel_payrolmgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_payrolmgmtLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jMonthChooser_payroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jYearChooser_payroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btn_process_payroll)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jpanel_payrolmgmtLayout.setVerticalGroup(
            jpanel_payrolmgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_payrolmgmtLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jpanel_payrolmgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jYearChooser_payroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMonthChooser_payroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_process_payroll))
                .addContainerGap(318, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpanel_payrolmgmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jpanel_payrolmgmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_process_payrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_process_payrollActionPerformed
        int selectedMonth = jMonthChooser_payroll.getMonth() + 1; // jMonthChooser indexes from 0 (Jan=0, Feb=1)
        int selectedYear = jYearChooser_payroll.getYear();

        PayrollProcessor payrollProcessor = new PayrollProcessor();
        payrollProcessor.processMonthlyPayroll(selectedYear, selectedMonth);
    }//GEN-LAST:event_btn_process_payrollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.
                    getLogger(PayrollManagement.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.
                    getLogger(PayrollManagement.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.
                    getLogger(PayrollManagement.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.
                    getLogger(PayrollManagement.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayrollManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_process_payroll;
    private com.toedter.calendar.JMonthChooser jMonthChooser_payroll;
    private com.toedter.calendar.JYearChooser jYearChooser_payroll;
    private javax.swing.JPanel jpanel_payrolmgmt;
    // End of variables declaration//GEN-END:variables
}
