/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import domain.EmployeeID;
import domain.Payslip;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import services.LoggerService;
import services.PayslipService;

/**
 *
 * @author brianjancarlos
 */
public class PayslipViewer extends javax.swing.JFrame {

    private final int employeeId;
    private PayslipService payslipService;

    /**
     * Creates new form PayslipViewer
     */
    public PayslipViewer(int employeeId) {
        initComponents();
        this.employeeId = employeeId;
        EmployeeID.empid = employeeId;
        setLocationRelativeTo(null);
        txt_empid.setText(String.valueOf(EmployeeID.empid));
        this.payslipService = new PayslipService();
        LoggerService.logInfo(
                " PayslipViewer: Requesting details for Employee ID: " + employeeId);
        // Fetch employee details
        loadPayPeriods();
    }

    private void loadPayPeriods() {
        List<String> payPeriods = payslipService.getAvailablePayPeriods();
        for (String period : payPeriods) {
            comboPayPeriods.addItem(period);
        }
        LoggerService.logInfo("Pay periods loaded: " + payPeriods.size());
    }

    private void fetchPayslip() {
        String employeeIdText = txt_empid.getText().trim();
        if (employeeIdText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an Employee ID.",
                    "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int employeeId;
        try {
            employeeId = Integer.parseInt(employeeIdText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Invalid Employee ID. Please enter a numeric value.",
                    "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String selectedPeriod = (String) comboPayPeriods.getSelectedItem();
        if (selectedPeriod == null) {
            JOptionPane.showMessageDialog(this, "No pay periods available.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] dates = selectedPeriod.split(" to ");
        String startDate = dates[0];
        String endDate = dates[1];

        Payslip payslip = payslipService.getPayslip(employeeId, startDate,
                endDate);
        if (payslip != null) {
            LoggerService.logInfo(
                    "Payslip fetched for Employee ID: " + employeeId + " | Period: " + selectedPeriod);
            txtPayslipDetails.setText(payslip.toString());
        } else {
            LoggerService.logWarning(
                    "No payslip found for Employee ID: " + employeeId + " in period: " + selectedPeriod);
            txtPayslipDetails.setText(
                    "No payslip found for Employee ID: " + employeeId + " for the selected period.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_payslip = new javax.swing.JPanel();
        lbl_empid = new javax.swing.JLabel();
        txt_empid = new javax.swing.JTextField();
        btnFetchPayslip = new javax.swing.JButton();
        comboPayPeriods = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPayslipDetails = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel_payslip.setBorder(javax.swing.BorderFactory.createTitledBorder("Payslip viewer"));

        lbl_empid.setText("Employee ID: ");

        txt_empid.setEnabled(false);

        btnFetchPayslip.setText("View Payslip");
        btnFetchPayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFetchPayslipActionPerformed(evt);
            }
        });

        txtPayslipDetails.setColumns(20);
        txtPayslipDetails.setRows(5);
        jScrollPane1.setViewportView(txtPayslipDetails);

        javax.swing.GroupLayout jPanel_payslipLayout = new javax.swing.GroupLayout(jPanel_payslip);
        jPanel_payslip.setLayout(jPanel_payslipLayout);
        jPanel_payslipLayout.setHorizontalGroup(
            jPanel_payslipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_payslipLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel_payslipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_payslipLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(jPanel_payslipLayout.createSequentialGroup()
                        .addComponent(lbl_empid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_empid, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboPayPeriods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnFetchPayslip)
                        .addGap(32, 32, 32))))
        );
        jPanel_payslipLayout.setVerticalGroup(
            jPanel_payslipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_payslipLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_payslipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_empid)
                    .addComponent(txt_empid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFetchPayslip)
                    .addComponent(comboPayPeriods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel_payslip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel_payslip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFetchPayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFetchPayslipActionPerformed
        fetchPayslip();
    }//GEN-LAST:event_btnFetchPayslipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayslipViewer.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayslipViewer.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayslipViewer.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayslipViewer.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayslipViewer(EmployeeID.empid).setVisible(true);
                LoggerService.logInfo("Payslip viewer started.");

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFetchPayslip;
    private javax.swing.JComboBox<String> comboPayPeriods;
    private javax.swing.JPanel jPanel_payslip;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_empid;
    private javax.swing.JTextArea txtPayslipDetails;
    private javax.swing.JTextField txt_empid;
    // End of variables declaration//GEN-END:variables
}
